"""Initial migration

Revision ID: bc38cf936955
Revises: 
Create Date: 2025-11-05 20:36:20.387499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc38cf936955'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fluxo', sa.Float(), nullable=False),
    sa.Column('pulso', sa.Integer(), nullable=False),
    sa.Column('sensor', sa.Integer(), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('h', sa.Float(), nullable=False),
    sa.Column('g', sa.Float(), nullable=False),
    sa.Column('solo', sa.Float(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packets_id'), 'packets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_packets_id'), table_name='packets')
    op.drop_table('packets')
    # ### end Alembic commands ###
